server:
  port: 0

spring:
  application:
    name: user-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: update
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/msa
#    username: admin
#    password: 1234
  main:
    allow-circular-references: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true

greeting:
  message: Welcome to the Simple E-commerce.


#token:
#  expiration_time: 86400000
management:
  endpoints:
    web:
      exposure:
        include: health, refresh, beans, busrefresh
#  secret: uA3dfn0QwGfz+pJHIymQs7eTnA1qx1JTYF93lh7EOqU=